package constant

const (
	TRANSACTION_SUCCESS   string = "SUCCESS"
	TRANSACTION_PENDING   string = "PENDING"
	TRANSACTION_PROCESS   string = "PROCESS"
	TRANSACTION_CANCELLED string = "CANCELLED"
	TRANSACTION_ROLLBACK  string = "ROLLBACK"
)
